

* Categorization of Solutions

Without restricting universality, alway consider the white face as starting point.

The nine colors of the cube are (b)lack, (w)hite, (y)ellow, (o)range, (d)ark-lue, (l)ight-blue, (g)reen, (r)ed, and (p)urple
For the following discussion I assume the following gird:


#+begin_src text
               +---+---+---+
               |   |   |   |  
               +---+---+---+
               |   | o |   |  
               +---+---+---+
               |   |   |   |  
               +---+---+---+
  +---+---+---++---+---+---++---+---+---+
  |   |   |   ||   |   |   ||   |   |   |  
  +---+---+---++---+---+---++---+---+---+
  |   | l |   ||   | b |   ||   | d |   |  
  +---+---+---++---+---+---++---+---+---+
  |   |   |   ||   |   |   ||   |   |   |  
  +---+---+---++---+---+---++---+---+---+
               +---+---+---+
               |   |   |   |  
               +---+---+---+
               |   | y |   |  
               +---+---+---+
               |   |   |   |  
               +---+---+---+
               +---+---+---+
               |   |   |   |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               |   |   |   |  
               +---+---+---+
#+end_src

Adjacent colors: yellow, light-blue, orange, blue
From this follow the opposite colors: yellow-orange, light-blue-blue, white-black

Generic solution types:
There are the following distinctions when categorizing solutions:

1. Type: Choose any of four adjacent color pairs as corners on the white face.
   E.g. orange-blue, yellow-light-blue, ...
   There are three possible positions to place the two colors on the white face
   2 adjacent and 1 diagonal placement (here at the example of orange and dark-blue):

         adjacent 1:
         #+begin_src text
               +---+---+---+
               | d |   | o |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               |   |   |   |  
               +---+---+---+
         #+end_src
         adjacent 2: 
         #+begin_src text
               +---+---+---+
               | o |   |   |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               | d |   |   |  
               +---+---+---+
         #+end_src
         diagonal
         #+begin_src text
               +---+---+---+
               |   |   | o |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               | d |   |   |  
               +---+---+---+
         #+end_src
         
   It needs to be further clarified how many possible solutions ervery type permits.      

         
2. Type: Choose two opposite colors.
   1. The two corners can only be placed diagonally on the face in two different positions:

         diagonal1
         #+begin_src text
               +---+---+---+
               | d |   |   |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               |   |   | l |  
               +---+---+---+
         #+end_src
         diagonal2
         #+begin_src text
               +---+---+---+
               |   |   | l |  
               +---+---+---+
               |   | w |   |  
               +---+---+---+
               | d |   |   |  
               +---+---+---+
         #+end_src 
      
